DROP SEQUENCE MYBOARDSEQ;

CREATE SEQUENCE MDBOARDSEQ;

CREATE TABLE MDBOARD(
	SEQ NUMBER PRIMARY KEY, 
	WRITER VARCHAR2(500) NOT NULL,
	TITLE VARCHAR2(100) NOT NULL,
	CONTENT VARCHAR2(2000) NOT NULL,
	REGDATE DATE NOT NULL
);

SELECT * FROM MDBOARD;

INSERT INTO MDBOARD VALUES(MDBOARDSEQ.NEXTVAL, '관리자', '테스트', 'TEST123456', SYSDATE);